steps:
    # 第一步：构建 Docker 镜像
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-chatbot:$SHORT_SHA', '.']

    # 第二步：推送镜像到 Google Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/react-chatbot:$SHORT_SHA']

    # 第三步：部署到 Google Cloud Run
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args:
          - 'run'
          - 'deploy'
          - 'react-chatbot'
          - '--image'
          - 'gcr.io/$PROJECT_ID/react-chatbot:$SHORT_SHA'
          - '--region'
          - 'australia-southeast1'
          - '--platform'
          - 'managed'
          - '--allow-unauthenticated'
          - '--port'
          - '80'

# 定义在构建后可用的镜像
images:
    - 'gcr.io/$PROJECT_ID/react-chatbot:$SHORT_SHA'
